import { useState, useEffect, useRef } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { useApp } from '@/context/AppContext';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Bell, CloudRain, AlertTriangle, Calendar, Droplets, Leaf,
  CheckCircle, Clock, Loader2, RefreshCw, X, FileText, MessageCircle
} from 'lucide-react';
import { toast } from 'sonner';
import { useNavigate } from 'react-router-dom';

interface SmartNotification {
  id: string; title: string; message: string; type: string;
  priority: string; action_type: string | null; action_data: any;
  read: boolean; dismissed: boolean; created_at: string;
}

const typeIcons: Record<string, typeof Bell> = {
  weather_alert: CloudRain, crop_risk: AlertTriangle, task_reminder: Calendar,
  nutrient_alert: Leaf, irrigation: Droplets, daily_summary: FileText, message_alert: MessageCircle,
};

const priorityColors: Record<string, string> = {
  high: 'bg-destructive/10 text-destructive border-destructive/30',
  normal: 'bg-primary/10 text-primary border-primary/30',
  low: 'bg-muted text-muted-foreground border-border',
};

export function SmartNotifications() {
  const { user } = useAuth();
  const { language } = useApp();
  const navigate = useNavigate();
  const [notifications, setNotifications] = useState<SmartNotification[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    if (user) {
      fetchNotifications();
      const channel = supabase
        .channel('smart_notifs')
        .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'smart_notifications', filter: `user_id=eq.${user.id}` }, (payload) => {
          setNotifications(prev => [payload.new as SmartNotification, ...prev]);
        })
        .subscribe();
      return () => { supabase.removeChannel(channel); };
    }
  }, [user]);

  const fetchNotifications = async () => {
    if (!user) return;
    const { data } = await supabase.from('smart_notifications').select('*').eq('user_id', user.id).eq('dismissed', false).order('created_at', { ascending: false }).limit(20);
    const notifs = (data || []) as SmartNotification[];
    setNotifications(notifs);
    setLoading(false);
    if (!hasAutoGenerated.current && notifs.length === 0) { hasAutoGenerated.current = true; generateNotifications(); }
    else if (!hasAutoGenerated.current && notifs.length > 0) {
      const latestTime = new Date(notifs[0].created_at).getTime();
      if (latestTime < Date.now() - 12 * 60 * 60 * 1000) { hasAutoGenerated.current = true; generateNotifications(); }
    }
  };

  const generateNotifications = async () => {
    if (!user) return;
    setGenerating(true);
    try {
      const { count: unreadCount } = await supabase.from('messages').select('*', { count: 'exact', head: true }).neq('sender_id', user.id).eq('read', false);
      const { error } = await supabase.functions.invoke('generate-smart-notifications', { body: { userId: user.id, language } });
      if (error) throw error;
      if (unreadCount && unreadCount > 0) {
        await supabase.from('smart_notifications').insert({
          user_id: user.id,
          title: language === 'hi' ? `${unreadCount} नए संदेश` : language === 'mr' ? `${unreadCount} नवीन संदेश` : `${unreadCount} new messages`,
          message: language === 'hi' ? 'समुदाय चैट देखें।' : language === 'mr' ? 'समुदाय चॅट पहा.' : 'Check community chat.',
          type: 'message_alert', priority: 'normal', action_type: 'view_messages',
          expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
        });
      }
      const threeDaysLater = new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0];
      const { data: upcomingEvents } = await supabase.from('calendar_events').select('*').eq('user_id', user.id).eq('completed', false).gte('event_date', new Date().toISOString().split('T')[0]).lte('event_date', threeDaysLater);
      if (upcomingEvents) {
        for (const event of upcomingEvents.slice(0, 2)) {
          const daysUntil = Math.ceil((new Date(event.event_date).getTime() - Date.now()) / 86400000);
          await supabase.from('smart_notifications').insert({
            user_id: user.id,
            title: `${event.crop_name} - ${event.event_type}`,
            message: language === 'hi' ? `${daysUntil} दिन में तैयारी करें` : language === 'mr' ? `${daysUntil} दिवसात तयारी करा` : `Prepare in ${daysUntil} day(s)`,
            type: 'task_reminder', priority: daysUntil <= 1 ? 'high' : 'normal', action_type: 'view_calendar',
            expires_at: new Date(event.event_date).toISOString(),
          });
        }
      }
      await fetchNotifications();
    } catch (error) { console.error('Generate error:', error); }
    finally { setGenerating(false); }
  };

  const dismissNotification = async (id: string) => {
    await supabase.from('smart_notifications').update({ dismissed: true, read: true }).eq('id', id);
    setNotifications(prev => prev.filter(n => n.id !== id));
  };

  const markRead = async (id: string) => {
    await supabase.from('smart_notifications').update({ read: true }).eq('id', id);
    setNotifications(prev => prev.map(n => n.id === id ? { ...n, read: true } : n));
  };

  const handleAction = async (notif: SmartNotification) => {
    await markRead(notif.id);
    switch (notif.action_type) {
      case 'view_calendar': navigate('/calendar'); break;
      case 'view_soil': navigate('/soil-report'); break;
      case 'view_messages': navigate('/community?tab=messages'); break;
      case 'mark_complete': await dismissNotification(notif.id); toast.success('Done!'); break;
      default: break;
    }
  };

  const actionLabels: Record<string, Record<string, string>> = {
    mark_complete: { en: 'Mark Done', hi: 'पूर्ण करें', mr: 'पूर्ण करा' },
    view_calendar: { en: 'View Calendar', hi: 'कैलेंडर देखें', mr: 'कॅलेंडर पहा' },
    view_soil: { en: 'Soil Report', hi: 'मिट्टी रिपोर्ट', mr: 'माती अहवाल' },
    view_messages: { en: 'View Messages', hi: 'संदेश देखें', mr: 'संदेश पहा' },
  };

  if (loading) return <div className="flex items-center justify-center p-8"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>;

  return (
    <Card className="flex flex-col" style={{ maxHeight: '500px' }}>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg flex items-center gap-2">
            <Bell className="h-5 w-5 text-primary" />
            {language === 'hi' ? 'स्मार्ट अलर्ट' : language === 'mr' ? 'स्मार्ट अलर्ट' : 'Smart Farming Alerts'}
            {generating && <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />}
          </CardTitle>
          <Button variant="outline" size="sm" onClick={generateNotifications} disabled={generating}>
            {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
          </Button>
        </div>
      </CardHeader>
      <CardContent className="overflow-y-auto flex-1">
        {notifications.length === 0 && !generating ? (
          <div className="text-center py-6">
            <Bell className="h-10 w-10 mx-auto text-muted-foreground/50 mb-2" />
            <p className="text-muted-foreground text-sm">{language === 'hi' ? 'कोई अलर्ट नहीं' : language === 'mr' ? 'कोणतेही अलर्ट नाहीत' : 'No alerts'}</p>
          </div>
        ) : (
          <div className="space-y-3">
            {notifications.map((notif) => {
              const Icon = typeIcons[notif.type] || Bell;
              return (
                <div key={notif.id}
                  className={`p-4 rounded-xl border transition-all ${priorityColors[notif.priority] || priorityColors.normal} ${!notif.read ? 'ring-2 ring-primary/20' : 'opacity-80'}`}>
                  <div className="flex items-start gap-3">
                    <Icon className="h-5 w-5 mt-0.5 shrink-0" />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="font-semibold text-sm">{notif.title}</span>
                        {notif.priority === 'high' && <Badge variant="destructive" className="text-xs px-1.5 py-0">{language === 'hi' ? 'ज़रूरी' : language === 'mr' ? 'तातडीचे' : 'Urgent'}</Badge>}
                      </div>
                      <p className="text-sm opacity-90">{notif.message}</p>
                      <div className="flex items-center gap-2 mt-2">
                        {notif.action_type && (
                          <Button size="sm" variant="secondary" className="h-7 text-xs" onClick={() => handleAction(notif)}>
                            {actionLabels[notif.action_type]?.[language] || actionLabels[notif.action_type]?.en || notif.action_type}
                          </Button>
                        )}
                        <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={() => dismissNotification(notif.id)}>
                          <X className="h-3 w-3 mr-1" />{language === 'hi' ? 'खारिज' : language === 'mr' ? 'नकारा' : 'Dismiss'}
                        </Button>
                      </div>
                    </div>
                    <span className="text-xs text-muted-foreground whitespace-nowrap">
                      <Clock className="h-3 w-3 inline mr-0.5" />
                      {new Date(notif.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
